apiVersion: apps/v1
kind: Deployment
metadata:
  name: asp-core-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asp-core-pod-template
  template:
    metadata:
      labels:
        app: asp-core-pod-template
    spec:
      containers:
      - name: asp-core-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # TODO: disabled the startup probe because it caused startup to take 90 seconds somehow...
        # startupProbe:
        #   httpGet:
        #     path: /Health
        #     port: 80
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        #   timeoutSeconds: 1
        #   failureThreshold: 10 # the application has 30 seconds to start
        ports:
        - containerPort: 80
        env:
        - name: Database__ConnectionString
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: Database__ConnectionString
        - name: Auth0__Domain
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: Auth0__Domain
        - name: DataProtection__PrivateKey
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DataProtection__PrivateKey
        - name: DataProtection__Certificate
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DataProtection__Certificate